<a href="https://colab.research.google.com/github/noelakki/sample_ai/blob/main/Hypothesis_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [34]:
with open('/content/drive/MyDrive/LSTM data/only_nlp_tech_available_tokens_train_16.5.pkl','rb') as fi:
  all_lst = pickle.load(fi)

In [35]:
df = pd.concat(all_lst)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 176259 entries, 1 to 877
Data columns (total 61 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   time                     176259 non-null  object
 1   high                     176259 non-null  float64
 2   low                      176259 non-null  float64
 3   open                     176259 non-null  float64
 4   close                    176259 non-null  float64
 5   symbol                   176259 non-null  object
 6   address                  176259 non-null  object
 7   volume                   176259 non-null  float64
 8   month                    176259 non-null  object
 9   year                     176259 non-null  object
 10  macd                     176259 non-null  float64
 11  macdsignal               176259 non-null  float64
 12  macdhist                 176259 non-null  float64
 13  rsi                      176259 non-null  float64
 14  ema                      176259 non-null  float64
 15  adx                      176259 non-null  float64
 16  aroondown                176259 non-null  float64
 17  aroonup                  176259 non-null  float64
 18  adosc                    176259 non-null  float64
 19  upperband                176259 non-null  float64
 20  middleband               176259 non-null  float64
 21  lowerband                176259 non-null  float64
 22  real                     176259 non-null  float64
 23  obv                      176259 non-null  float64
 24  slowk                    176259 non-null  float64
 25  slowd                    176259 non-null  float64
 26  macd_f1                  176259 non-null  float64
 27  macd_f2                  176259 non-null  int64
 28  macd_f3                  176259 non-null  float64
 29  adosc_f1                 176259 non-null  float64
 30  adosc_f2                 176259 non-null  float64
 31  adosc_f3                 176259 non-null  float64
 32  rsi_f1                   176259 non-null  int64
 33  rsi_f2                   176259 non-null  float64
 34  ema_f2                   176259 non-null  float64
 35  ema_f1                   176259 non-null  float64
 36  scoh_f1                  176259 non-null  float64
 37  scoh_f2                  176259 non-null  float64
 38  scoh_f3                  176259 non-null  int64
 39  scoh_f4                  176259 non-null  float64
 40  adx_f1                   176259 non-null  int64
 41  adx_f2                   176259 non-null  float64
 42  aroon_f1                 176259 non-null  float64
 43  aroon_f2                 176259 non-null  float64
 44  bband_f1                 176259 non-null  int64
 45  bband_f2                 176259 non-null  float64
 46  num_tweets               176259 non-null  float64
 47  num_positive_tweets      176259 non-null  float64
 48  num_negative_tweets      176259 non-null  float64
 49  num_neutral_tweets       176259 non-null  float64
 50  NUM_POSITIVE_LIKES       176259 non-null  float64
 51  NUM_NEGATIVE_LIKES       176259 non-null  float64
 52  NUM_NEUTRAL_LIKES        176259 non-null  float64
 53  daily_sentiment          176259 non-null  float64
 54  daily_sentiment_30_days  176259 non-null  float64
 55  long_term_sentiment      176259 non-null  float64
 56  relative_tweet_volume    176259 non-null  float64
 57  num_unique_accounts      176259 non-null  float64
 58  M                        176259 non-null  float64
 59  Date1                    176259 non-null  datetime64[ns]
 60  target                   176259 non-null  object
dtypes: datetime64[ns](1), float64(49), int64(5), object(6)
memory usage: 83.4+ MB

In [28]:
features_list = ['macd', 'macdsignal', 'macdhist', 'rsi', 'ema', 'adx',
       'aroondown', 'aroonup', 'adosc', 'upperband', 'middleband', 'lowerband',
       'real', 'obv', 'slowk', 'slowd', 'macd_f1', 'macd_f2', 'macd_f3',
       'adosc_f1', 'adosc_f2', 'adosc_f3', 'rsi_f1', 'rsi_f2', 'ema_f2',
       'ema_f1', 'scoh_f1', 'scoh_f2', 'scoh_f3', 'scoh_f4', 'adx_f1',
       'adx_f2', 'aroon_f1', 'aroon_f2', 'bband_f1', 'bband_f2','num_tweets',
       'num_positive_tweets', 'num_negative_tweets', 'num_neutral_tweets',
       'NUM_POSITIVE_LIKES', 'NUM_NEGATIVE_LIKES', 'NUM_NEUTRAL_LIKES',
       'daily_sentiment', 'daily_sentiment_30_days', 'long_term_sentiment',
       'relative_tweet_volume', 'num_unique_accounts']

In [13]:
from scipy.stats import chi2_contingency

In [39]:
dt = {'feature':[],'p':[]}
for ft in features_list:
  stat, p, dof, expected = chi2_contingency(pd.crosstab(df[ft], df['target']))
  dt['feature'].append(ft)
  dt['p'].append(p)

In [40]:
pd.DataFrame(dt)

                    feature             p
0                      macd  4.546285e-01
1                macdsignal  4.546285e-01
2                  macdhist  4.546285e-01
3                       rsi  1.092871e-03
4                       ema  4.546285e-01
5                       adx  4.948487e-01
6                 aroondown  1.822685e-68
7                   aroonup  2.448638e-72
8                     adosc  4.988801e-01
9                 upperband  5.146966e-02
10               middleband  3.954428e-03
11                lowerband  5.164826e-02
12                     real  4.362842e-01
13                      obv  3.921943e-07
14                    slowk  5.725440e-02
15                    slowd  4.187432e-01
16                  macd_f1  2.344760e-05
17                  macd_f2  8.985697e-01
18                  macd_f3  7.668399e-01
19                 adosc_f1  4.988801e-01
20                 adosc_f2  1.870167e-01
21                 adosc_f3  1.756246e-01
22                   rsi_f1  2.398191e-21
23                   rsi_f2  4.980039e-12
24                   ema_f2  9.688431e-20
25                   ema_f1  4.559641e-01
26                  scoh_f1  5.951774e-02
27                  scoh_f2  3.097179e-03
28                  scoh_f3  3.419552e-06
29                  scoh_f4  6.527684e-09
30                   adx_f1  8.601223e-02
31                   adx_f2  1.909589e-12
32                 aroon_f1  1.925313e-02
33                 aroon_f2  1.070325e-01
34                 bband_f1  4.495622e-03
35                 bband_f2  2.979533e-02
36               num_tweets  1.454255e-09
37      num_positive_tweets  5.598204e-10
38      num_negative_tweets  6.208336e-03
39       num_neutral_tweets  3.531474e-02
40       NUM_POSITIVE_LIKES  1.346568e-01
41       NUM_NEGATIVE_LIKES  9.005074e-01
42        NUM_NEUTRAL_LIKES  3.458020e-01
43          daily_sentiment  1.884082e-05
44  daily_sentiment_30_days  1.997802e-08
45      long_term_sentiment  6.839044e-14
46    relative_tweet_volume  4.053552e-05
47      num_unique_accounts  5.962997e-10

In [41]:
pd.DataFrame(dt).to_csv('Chi_Square_16_5.csv',index=False)